image: node:10

cache:
  paths:
    - node_modules/ # Node modules and dependencies

before_script:
  - npm install gitbook-cli -g # install gitbook
  - gitbook fetch 3.2.3 # fetch latest stable version
  - gitbook install # add any requested plugins in book.json

pages:
  stage: deploy
  script:
    - gitbook build . public # build to public path
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master # this job will affect only
 the 'master' branch


# eschillus-syntax theme

## A bright and colorful syntax theme to please your eyes at all times.

![Skärmavbild 2020-05-16 kl  18 40 47](https://user-images.githubusercontent.com/50766600/82125341-a6ad6180-97a5-11ea-95e0-3c0492d95db9.png)
